Bootstrap:docker
From:vustruct/ensembl_perlapi

%runscript
        /bin/bash

%environment
    export CONTAINER_TYPE=Singularity

%post -c bin/bash
    CUSTOM_PS1_SCRIPT=/.singularity.d/env/pipeline_ps1_setup.sh
    cat > $CUSTOM_PS1_SCRIPT << EOF
PS1='\r\n\[$(/usr/bin/tput setaf 195; /usr/bin/tput setab 033)\]   ensembl_perlapi    host:\h  user:\u      Singularity Container\[$(/usr/bin/tput sgr0)\]\r\n\w\$ '
#export PS1
EOF
    chmod 755 $CUSTOM_PS1_SCRIPT
